### ISSUE TITLE
Support various languages on the new API

### ISSUE THREAD

**Issue by wargio** [wargio/plugin.video.southpark_unofficial#27]
The new apis has broken the addon 

- [x] English | North America (helix: https://github.com/xbmc/repo-plugins/pull/3132 matrix: https://github.com/xbmc/repo-plugins/pull/3131)
- [x] German | Germany (helix: xbmc/repo-plugins#3155 matrix: xbmc/repo-plugins#3154)
- [x] Spanish | North America (helix: xbmc/repo-plugins#3155 matrix: xbmc/repo-plugins#3154)
- [x] Swedish | Sweden (helix: xbmc/repo-plugins#3155 matrix: xbmc/repo-plugins#3154)
- [x] Spanish | South America https://github.com/wargio/plugin.video.southpark_unofficial/issues/30

Ok, US users might experience ads.

Linked to: https://github.com/wargio/plugin.video.southpark_unofficial/issues/26

**Comment by Matheos96** [comment]
> The new apis has broken the addon
> 
> * [x]  English (helix: [xbmc/repo-plugins#3132](https://github.com/xbmc/repo-plugins/pull/3132) matrix: [xbmc/repo-plugins#3131](https://github.com/xbmc/repo-plugins/pull/3131))
> * [ ]  German
> * [ ]  Spanish
> * [ ]  Swedish
> 
> Linked to: #26

Will we be able to use the English version in Finland while the swedish is unavailable? When I go to southparkstudios in browser I get redirected to .nu (which I assume is SWE), but that redirect is probably just because of location and not content restrictions?

**Comment by wargio** [comment]
It should work. i tried this with the VPN and i didn't have issues.
The only weird thing you might experience is titles in your language.

**Comment by Matheos96** [comment]
> It should work. i tried this with the VPN and i didn't have issues.
> The only weird thing you might experience is titles in your language.

Ok thanks. We have never seen any titles in any of our two official languages (Swedish and Finnish), so I think we won't have that problem now either (not that it would matter). Excited for the update :)

**Comment by beachmiles** [comment]
The 0.6.0 version is still not working here in the US, looks like it trying to access /tmp/test.html which isn't accessible. Here is the kodi error log I just captured.
https://github.com/wargio/plugin.video.southpark_unofficial/issues/26#issuecomment-703066011

**Comment by wargio** [comment]
@Matheos96 can you try this version? https://github.com/wargio/plugin.video.southpark_unofficial/archive/langs-new-apis.zip has SWE lang (and as well, de, es..)

I've tried to unify all the apis in a more simple way.

**Comment by kloklojul** [comment]
Works for germany

**Comment by beachmiles** [comment]
Loaded the zipped version above on kodi in us english and was seeing episodes start with an ad and then the episode audio only with no video.
I found that hitting back and restarting the episode a couple times got the episode video eventually to show.

**Comment by floreno** [comment]
> Works for germany
Can confirm, works like a charme :)
Just “random episodes” throws exception: “KeyError: ‘locked’” for the episode_data['locked'] var.
Thank u so much for ur work on the plug-in!

**Comment by wargio** [comment]
> Loaded the zipped version above on kodi in us english and was seeing episodes start with an ad and then the episode audio only with no video.
> I found that hitting back and restarting the episode a couple times got the episode video eventually to show.

unfortunately i can't patch that. i had the same issue with the spanish version.
i can try to kinda enforce the splitted episodes.

**Comment by wargio** [comment]
@beachmiles you do not need to update the addon, but just delete the `southpark` folder from `temp` in the kodi folder.

**Comment by Matheos96** [comment]
> @Matheos96 can you try this version? https://github.com/wargio/plugin.video.southpark_unofficial/archive/langs-new-apis.zip has SWE lang (and as well, de, es..)
> 
> I've tried to unify all the apis in a more simple way.

I tried installing this version now. Removed ~/.kodi/temp/southpark too and everything looked OK. Got into seasons and chose episode but it never loaded. I guess this is the HLS error you were talking about earlier in another issue? (I retried many times as you can see from the log. Even more than this)

```
2020-10-04 17:02:07.223 T:3011920480   ERROR: Control 550 in window 10025 has been asked to focus, but it can't
2020-10-04 17:02:09.384 T:2309882736   ERROR: [sp.addon] expected string or buffer
2020-10-04 17:02:18.438 T:3011920480   ERROR: Previous line repeats 1 times.
2020-10-04 17:02:18.438 T:3011920480  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=22&episode=9
2020-10-04 17:02:18.671 T:2338747248  NOTICE: Creating InputStream
2020-10-04 17:02:18.863 T:2338747248  NOTICE: Creating Demuxer
2020-10-04 17:02:18.863 T:2338747248  NOTICE: Opening stream: 1001 source: 256
2020-10-04 17:02:19.220 T:2338747248 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.
2020-10-04 17:02:19.220 T:2338747248  NOTICE: Opening stream: 1002 source: 256
2020-10-04 17:02:19.220 T:2338747248  NOTICE: Finding audio codec for: 86018
2020-10-04 17:02:19.221 T:2338747248  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-10-04 17:02:19.221 T:2338747248  NOTICE: Creating audio thread
2020-10-04 17:02:19.221 T:2321961840  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-10-04 17:02:19.221 T:2338747248  NOTICE: CVideoPlayer::OnExit()
2020-10-04 17:02:19.221 T:2338747248  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-10-04 17:02:19.222 T:2338747248  NOTICE: Closing stream player 1
2020-10-04 17:02:19.222 T:2338747248  NOTICE: Waiting for audio thread to exit
2020-10-04 17:02:19.231 T:2321961840  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-10-04 17:02:19.231 T:2338747248  NOTICE: Closing audio device
2020-10-04 17:02:19.231 T:2338747248  NOTICE: Deleting audio codec
2020-10-04 17:02:19.277 T:3011920480  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 17:02:19.278 T:3011920480  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 17:02:19.278 T:3011920480  NOTICE: VideoPlayer: finished waiting
2020-10-04 17:02:19.278 T:3011920480  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 17:02:19.278 T:3011920480  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 17:02:19.278 T:3011920480  NOTICE: VideoPlayer: finished waiting
2020-10-04 17:02:22.496 T:2309882736   ERROR: [sp.addon] expected string or buffer
2020-10-04 17:02:23.688 T:3011920480  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=22&episode=9
2020-10-04 17:02:23.822 T:2142819184  NOTICE: Creating InputStream
2020-10-04 17:02:24.003 T:2142819184  NOTICE: Creating Demuxer
2020-10-04 17:02:24.004 T:2142819184  NOTICE: Opening stream: 1001 source: 256
2020-10-04 17:02:24.350 T:2142819184 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.
2020-10-04 17:02:24.350 T:2142819184  NOTICE: Opening stream: 1002 source: 256
2020-10-04 17:02:24.350 T:2142819184  NOTICE: Finding audio codec for: 86018
2020-10-04 17:02:24.350 T:2142819184  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-10-04 17:02:24.350 T:2142819184  NOTICE: Creating audio thread
2020-10-04 17:02:24.351 T:2330354544  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-10-04 17:02:24.351 T:2142819184  NOTICE: CVideoPlayer::OnExit()
2020-10-04 17:02:24.351 T:2142819184  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-10-04 17:02:24.351 T:2142819184  NOTICE: Closing stream player 1
2020-10-04 17:02:24.356 T:2142819184  NOTICE: Waiting for audio thread to exit
2020-10-04 17:02:24.361 T:2330354544  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-10-04 17:02:24.361 T:2142819184  NOTICE: Closing audio device
2020-10-04 17:02:24.361 T:2142819184  NOTICE: Deleting audio codec
2020-10-04 17:02:24.377 T:3011920480  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 17:02:24.377 T:3011920480  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 17:02:24.377 T:3011920480  NOTICE: VideoPlayer: finished waiting
2020-10-04 17:02:24.377 T:3011920480  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 17:02:24.377 T:3011920480  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 17:02:24.377 T:3011920480  NOTICE: VideoPlayer: finished waiting
2020-10-04 17:02:25.259 T:2309882736   ERROR: [sp.addon] expected string or buffer
2020-10-04 17:02:26.331 T:3011920480  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=22&episode=9

```

**Comment by wargio** [comment]
`2020-10-04 17:02:24.350 T:2142819184 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.` @Matheos96 
yes yo do not support HLS.

**Comment by Matheos96** [comment]
> `2020-10-04 17:02:24.350 T:2142819184 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.` @Matheos96 
> Yes your device do not support HLS.

Ah crap. Well I dont really understand. Because when I manually ripped the stream m3us from the source on southparkstudios.nu, I could easily play these m3u files on this device.

**Comment by wargio** [comment]
via kodi?

**Comment by Matheos96** [comment]
@wargio Yes. Same device and same OS (Kodi 18)

**Comment by wargio** [comment]
then i have no clue. can you try with kodi on a computer?

**Comment by Matheos96** [comment]
Yes I can, and I did. Latest Windows build. Worked fine with the zip you linked above. I see the one same error in the log though, but the stream does play.

```
2020-10-04 18:52:58.547 T:20512   ERROR: [sp.addon] expected string or buffer
2020-10-04 18:53:03.703 T:20248   ERROR: Previous line repeats 1 times.
2020-10-04 18:53:03.703 T:20248  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=22&episode=10
2020-10-04 18:53:03.959 T:20588  NOTICE: Creating InputStream
2020-10-04 18:53:04.206 T:20588  NOTICE: Creating Demuxer
2020-10-04 18:53:07.558 T:20588  NOTICE: Opening stream: 9 source: 256
2020-10-04 18:53:07.558 T:20588  NOTICE: Creating video codec with codec id: 27
2020-10-04 18:53:07.558 T:20588  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2020-10-04 18:53:07.558 T:20588  NOTICE: Creating video thread
2020-10-04 18:53:07.558 T:23532  NOTICE: running thread: video_thread
2020-10-04 18:53:07.561 T:20588  NOTICE: Opening stream: 8 source: 256
2020-10-04 18:53:07.561 T:20588  NOTICE: Finding audio codec for: 86018
2020-10-04 18:53:07.561 T:20588  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-10-04 18:53:07.561 T:20588  NOTICE: Creating audio thread
2020-10-04 18:53:07.562 T:14636  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-10-04 18:53:07.730 T:14636  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2020-10-04 18:53:07.794 T:20248  NOTICE: DXVA::CProcessorHD::InitProcessor: supported deinterlace methods: blend:yes, bob:yes, adaptive:yes, mocomp:no.
2020-10-04 18:53:07.795 T:20248 WARNING: CWinRenderer::UpdateVideoFilter: chosen scaling method 1 is not supported by renderer
2020-10-04 18:53:08.151 T:23532  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41708
2020-10-04 18:53:13.184 T:20248  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 18:53:13.184 T:20248  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 18:53:13.187 T:20588  NOTICE: CVideoPlayer::OnExit()
2020-10-04 18:53:13.187 T:20588  NOTICE: Closing stream player 1
2020-10-04 18:53:13.187 T:20588  NOTICE: Waiting for audio thread to exit
2020-10-04 18:53:13.213 T:14636  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-10-04 18:53:13.213 T:20588  NOTICE: Closing audio device
2020-10-04 18:53:13.227 T:20588  NOTICE: Deleting audio codec
2020-10-04 18:53:13.227 T:20588  NOTICE: Closing stream player 2
2020-10-04 18:53:13.227 T:20588  NOTICE: waiting for video thread to exit
2020-10-04 18:53:13.270 T:23532  NOTICE: thread end: video_thread
2020-10-04 18:53:13.270 T:20588  NOTICE: deleting video codec
2020-10-04 18:53:13.270 T:20588  NOTICE: DXVA::CDecoder::Close: closing decoder.
2020-10-04 18:53:13.270 T:20588  NOTICE: DXVA: closing decoder context.
2020-10-04 18:53:13.272 T:20248  NOTICE: VideoPlayer: finished waiting
2020-10-04 18:53:13.272 T:20248  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 18:53:13.272 T:20248  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 18:53:13.272 T:20248  NOTICE: VideoPlayer: finished waiting
2020-10-04 18:53:13.285 T:20248   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-10-04 18:53:13.306 T:20512   ERROR: [sp.addon] expected string or buffer
2020-10-04 18:53:16.103 T:20248   ERROR: Previous line repeats 1 times.
2020-10-04 18:53:16.103 T:20248  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=22&episode=9
2020-10-04 18:53:16.232 T:6780  NOTICE: Creating InputStream
2020-10-04 18:53:16.363 T:6780  NOTICE: Creating Demuxer
2020-10-04 18:53:18.964 T:6780  NOTICE: Opening stream: 9 source: 256
2020-10-04 18:53:18.964 T:6780  NOTICE: Creating video codec with codec id: 27
2020-10-04 18:53:18.964 T:6780  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2020-10-04 18:53:18.964 T:6780  NOTICE: Creating video thread
2020-10-04 18:53:18.964 T:5820  NOTICE: running thread: video_thread
2020-10-04 18:53:18.964 T:6780  NOTICE: Opening stream: 8 source: 256
2020-10-04 18:53:18.964 T:6780  NOTICE: Finding audio codec for: 86018
2020-10-04 18:53:18.964 T:6780  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-10-04 18:53:18.964 T:6780  NOTICE: Creating audio thread
2020-10-04 18:53:18.964 T:4196  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-10-04 18:53:19.311 T:4196  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2020-10-04 18:53:19.335 T:20248  NOTICE: DXVA::CProcessorHD::InitProcessor: supported deinterlace methods: blend:yes, bob:yes, adaptive:yes, mocomp:no.
2020-10-04 18:53:19.336 T:20248 WARNING: CWinRenderer::UpdateVideoFilter: chosen scaling method 1 is not supported by renderer
2020-10-04 18:53:20.017 T:5820  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41708
2020-10-04 18:53:21.584 T:20248  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 18:53:21.584 T:20248  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 18:53:21.586 T:6780  NOTICE: CVideoPlayer::OnExit()
2020-10-04 18:53:21.586 T:6780  NOTICE: Closing stream player 1
2020-10-04 18:53:21.586 T:6780  NOTICE: Waiting for audio thread to exit
2020-10-04 18:53:21.599 T:4196  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-10-04 18:53:21.599 T:6780  NOTICE: Closing audio device
2020-10-04 18:53:21.614 T:6780  NOTICE: Deleting audio codec
2020-10-04 18:53:21.614 T:6780  NOTICE: Closing stream player 2
2020-10-04 18:53:21.614 T:6780  NOTICE: waiting for video thread to exit
2020-10-04 18:53:21.617 T:5820  NOTICE: thread end: video_thread
2020-10-04 18:53:21.617 T:6780  NOTICE: deleting video codec
2020-10-04 18:53:21.617 T:6780  NOTICE: DXVA::CDecoder::Close: closing decoder.
2020-10-04 18:53:21.617 T:6780  NOTICE: DXVA: closing decoder context.
2020-10-04 18:53:21.618 T:20248  NOTICE: VideoPlayer: finished waiting
2020-10-04 18:53:21.618 T:20248  NOTICE: CVideoPlayer::CloseFile()
2020-10-04 18:53:21.618 T:20248  NOTICE: VideoPlayer: waiting for threads to exit
2020-10-04 18:53:21.618 T:20248  NOTICE: VideoPlayer: finished waiting
2020-10-04 18:53:21.631 T:20248   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-10-04 18:53:21.657 T:20512   ERROR: [sp.addon] expected string or buffer
```

**Comment by wargio** [comment]
then i really do not know what is wrong with librelec.

**Comment by Matheos96** [comment]
I am wondering if it could be this https://github.com/peak3d/inputstream.adaptive/issues/131

But they claim that it is fixed. Or can something somehow have been left from the previous versions of the addon? Is there any other folder I could try to delete?
Like for example if the streams are cached, I noticed they expire after some hours (expiration in the URL). I had ripped some streams manually earlier and it acted quite the same when trying to play ripped streams that had expired. Just speculating though.

**Comment by wargio** [comment]
i really do not know. my only suggestion is to use kodi builds, and not libreelec

**Comment by Matheos96** [comment]
> i really do not know. my only suggestion is to use kodi builds, and not libreelec

Well on a raspberry pi that is not an option as there are no official kodi builds for raspberry pi. LibreElec, OSMC and xbian are the recommended distributions for Kodi on RPi

**Comment by wargio** [comment]
0.6.2 on its way: https://github.com/xbmc/repo-plugins/pull/3154 and https://github.com/xbmc/repo-plugins/pull/3155

**Comment by kloklojul** [comment]
Haven't tested 6.2 but installing the linked zip from above works on a raspberry pi 3 with libreelec and on a fresh pi0w also with libreelec

**Comment by Milli-Maci** [comment]
I have the same problem as Matheos96. 
Running 0.6.2. Episodes show up but when I try to play an episode, it tries to load it but nothing happens. The episode is then marked as played. 
I'm running kodi 18.8 on Arch so I guess HLS is the issue here too.
Would this be of any help? 
https://github.com/xbmc/inputstream.ffmpegdirect

**Comment by wargio** [comment]
i'll investigate on this a bit more. thanks for reporting the same issue on arch. i use arch and i do not have that issue.

**Comment by Milli-Maci** [comment]
> i'll investigate on this a bit more. thanks for reporting the same issue on arch. i use arch and i do not have that issue.

I must be missing something that you do have in your Arch install. If I can be of any help, please let me know.

**Comment by Isayso** [comment]
FYI: running 0.6.2 upgrading from 0.6.1 and had to delete all files in .kodi/temp/southpark on libreelec 18.3 RPi3+

**Comment by Milli-Maci** [comment]
After deleting the add-on, running a full system update, restarting and re-installing the add-on, it started working. I had already removed and re-installed to no avail. My last system update has been 2 or 3 months.
Maybe just the reboot did it. I have no idea.
Anyway, 0.6.2 works on Arch.

**Comment by Milli-Maci** [comment]
I have to give an update.
On the first day, almost all episodes could be played. On the second day half of them stopped working and now none plays anymore. On the second day, I even got strange messages as "episode banned" on some of the episodes in de 22nd season.

**Comment by wargio** [comment]
> I have to give an update.
> On the first day, almost all episodes could be played. On the second day half of them stopped working and now none plays anymore. On the second day, I even got strange messages as "episode banned" on some of the episodes in de 22nd season.

Configuration?

**Comment by eldergabriel** [comment]
> > `2020-10-04 17:02:24.350 T:2142819184 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.` @Matheos96
> > Yes your device do not support HLS.
> 
> Ah crap. Well I dont really understand. Because when I manually ripped the stream m3us from the source on southparkstudios.nu, I could easily play these m3u files on this device.

Sorry so verbose, but...
Yeah, I'm seeing this message in the log file, too. I'm running osmc and kodi on a raspberry pi 2 (model B, I think). I haven't tried a fresh install recently, but it is all fully up to date (afaik), including the south park addon. I did get rid of the cache, and made sure the addon was updated before trying it again. Up until that point, I was having other problems, but now everything seems fine with the addon, except when it comes to playing episodes. It acts like it's going to play the episode, but then it doesn't, and just returns to the list of episodes for the season that you were just looking at.

I don't understand the HLS situation, either. The addon played episodes just fine until they changed the api a few weeks ago. Maybe I'm thinking a little too simplistically, but the api is just an interface, so I wouldn't necessarily expect that to result in an inability to play the same video streams. Ergo, once the api differences are accounted for, all other things remaining equal, one is tempted to think that the addon would then function as normal. Would they really have made such a radical change to the underlying delivery and transport methodology just because of, or in conjunction with, an api change? I.e. do we know for a fact that HLS support is apparently now required for playing back their video streams when it wasn't just a few weeks ago?

And what about being able to play those m3u files as you mentioned? I'm not sure what method you used to do that, but if I could download (wget / curl?) some of those stream m3us, I'd like to try manually testing playback (preferably English). If those playback ok, wouldn't that suggest that there is more to the situation that just HLS support?

**Comment by Matheos96** [comment]
> > > `2020-10-04 17:02:24.350 T:2142819184 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.` @Matheos96
> > > Yes your device do not support HLS.
> > 
> > 
> > Ah crap. Well I dont really understand. Because when I manually ripped the stream m3us from the source on southparkstudios.nu, I could easily play these m3u files on this device.
> 
> Sorry so verbose, but...
> Yeah, I'm seeing this message in the log file, too. I'm running osmc and kodi on a raspberry pi 2 (model B, I think). I haven't tried a fresh install recently, but it is all fully up to date (afaik), including the south park addon. I did get rid of the cache, and made sure the addon was updated before trying it again. Up until that point, I was having other problems, but now everything seems fine with the addon, except when it comes to playing episodes. It acts like it's going to play the episode, but then it doesn't, and just returns to the list of episodes for the season that you were just looking at.
> 
> I don't understand the HLS situation, either. The addon played episodes just fine until they changed the api a few weeks ago. Maybe I'm thinking a little too simplistically, but the api is just an interface, so I wouldn't necessarily expect that to result in an inability to play the same video streams. Ergo, once the api differences are accounted for, all other things remaining equal, one is tempted to think that the addon would then function as normal. Would they really have made such a radical change to the underlying delivery and transport methodology just because of, or in conjunction with, an api change? I.e. do we know for a fact that HLS support is apparently now required for playing back their video streams when it wasn't just a few weeks ago?
> 
> And what about being able to play those m3u files as you mentioned? I'm not sure what method you used to do that, but if I could download (wget / curl?) some of those stream m3us, I'd like to try manually testing playback (preferably English). If those playback ok, wouldn't that suggest that there is more to the situation that just HLS support?

To answer your last paragraph: I used chrome dev tools inspection "Network" tab to inspect the traffic while turning on the video on the southpark website. From there I found the .m3u links, I then saved the links into a simple text file and renamed it something.m3u (you need to rip 3 m3u links from network tab, as the episodes on southparkstudios.nu at least, are split into parts which are loaded once needed). Now this m3u file you created with the following syntax:
```
#EXTINF:-1, Part1
http://link1

#EXTINF:-1, Part2
http://link2

#EXTINF:-1, Part3
http://link3
```
will be playable on kodi, either transfer it via SFTP, SSH or put int on a share which is accessible from kodi.

Note that each m3u link you rip have an expiration date in UNIXTIME in the URL, meaning it will most likely not work if you wait too many hours to play it.

Cheers

**Comment by wargio** [comment]
> > > `2020-10-04 17:02:24.350 T:2142819184 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.` @Matheos96
> > > Yes your device do not support HLS.
> > 
> > 
> > Ah crap. Well I dont really understand. Because when I manually ripped the stream m3us from the source on southparkstudios.nu, I could easily play these m3u files on this device.
> 
> Sorry so verbose, but...
> Yeah, I'm seeing this message in the log file, too. I'm running osmc and kodi on a raspberry pi 2 (model B, I think). I haven't tried a fresh install recently, but it is all fully up to date (afaik), including the south park addon. I did get rid of the cache, and made sure the addon was updated before trying it again. Up until that point, I was having other problems, but now everything seems fine with the addon, except when it comes to playing episodes. It acts like it's going to play the episode, but then it doesn't, and just returns to the list of episodes for the season that you were just looking at.
> 
> I don't understand the HLS situation, either. The addon played episodes just fine until they changed the api a few weeks ago. Maybe I'm thinking a little too simplistically, but the api is just an interface, so I wouldn't necessarily expect that to result in an inability to play the same video streams. Ergo, once the api differences are accounted for, all other things remaining equal, one is tempted to think that the addon would then function as normal. Would they really have made such a radical change to the underlying delivery and transport methodology just because of, or in conjunction with, an api change? I.e. do we know for a fact that HLS support is apparently now required for playing back their video streams when it wasn't just a few weeks ago?
> 
> And what about being able to play those m3u files as you mentioned? I'm not sure what method you used to do that, but if I could download (wget / curl?) some of those stream m3us, I'd like to try manually testing playback (preferably English). If those playback ok, wouldn't that suggest that there is more to the situation that just HLS support?

actually is not that simple. with the new apis, there are 2 types of streams. the splitted ones and the ads included ones.

with the first ones, i can request rtmps or hls. with the 2nd one only hls.

The issue with the new implemementation is that i do not have an easy way to get the streams if not by parsing the html page (i need some uuid) then i have to make several requests to just fetch 1 episode, which is stupid.

The biggest issue i'm facing besides this, is that even if the webpage looks the same, it is not. the data is in different locations based purely on when they update it.

So i'm still trying to find a solution to all this which does not imply you waiting 50 mins to just fetch all the episode list.

**Comment by wargio** [comment]
anyway, if you want me to patch this again, i need to know which country you are in and what the settings are on your kodi for the addon.

- Country:
- Language:
- Geolocation:
- Subs [on/off]

**Comment by eldergabriel** [comment]
> > And what about being able to play those m3u files as you mentioned? I'm not sure what method you used to do that, but if I could download (wget / curl?) some of those stream m3us, I'd like to try manually testing playback (preferably English). If those playback ok, wouldn't that suggest that there is more to the situation that just HLS support?
> 
> To answer your last paragraph: I used chrome dev tools inspection "Network" tab to inspect the traffic while turning on the video on the southpark website. From there I found the .m3u links, I then saved the links into a simple text file and renamed it something.m3u (you need to rip 3 m3u links from network tab, as the episodes on southparkstudios.nu at least, are split into parts which are loaded once needed). Now this m3u file you created with the following syntax:
> 
> ```
> #EXTINF:-1, Part1
> http://link1
> 
> #EXTINF:-1, Part2
> http://link2
> 
> #EXTINF:-1, Part3
> http://link3
> ```
> 
> will be playable on kodi, either transfer it via SFTP, SSH or put int on a share which is accessible from kodi.
> 
> Note that each m3u link you rip have an expiration date in UNIXTIME in the URL, meaning it will most likely not work if you wait too many hours to play it.
> 
> Cheers
> 
> **Addition**
> As you see here, I started to play the video. My progress in the video is before the first yellow mark on the timeline. This is part1. I said there are three parts, but in reality there are four, but I genereally skip the first one as it is only the intro... You can see how I copy the m3u link for the part in question. Sort the network tab by Name to find the _stream.....1920x1080_ link.
> Now once copied you have one part. Paste into a file like I showed above. Now I recommend cleaning the network tab and moving the progress thingy to somewhere inside the next part, this will cause the generation of the next needed link, copy the _stream..._ link that appears. Paste into your file as part2 and repeat for part3 and 4.. If you don't clean the tab, it gets confusing quickly what stream is what part. Also note that sometimes there are multiple streams loaded for the same part, these often differ in terms of resolution of the video, the link will indicate this.

Wow, thanks for the thorough and detailed explanation. I'll have to give that a try when I get a chance.

In your experience, how consistent are the links? I.e. if you watch an episode and save those links to an m3u file, flush your browser cache, history, etc., close and reopen your browser, then watch that same episode again, are those links identical? Wargio's reply just below suggests that we are dealing with quasi-random, dynamically generated urls, which understandably complicates things.

**Comment by wargio** [comment]
those links are automatically generated and expires.

**Comment by Matheos96** [comment]
@eldergabriel 

> those links are automatically generated and expires. those are not cachable.

Exactly. I have not checked if you are ever given the same link if you reload within 50minutes or whatever, but bottom line is that they do expire and that they cannot be cached as wagio says. They should be loaded every time you launch the addon or open a certain season or something. 

What I explained is nothing new to devs I assume, I just wanted you to know how I "tested" the streams manually without an addon with the new API.

Also, welcome. Hope it helps

**Comment by wargio** [comment]
i've just updated all the swe streams. let me know if you have more issues (this was an update on the addon data, not on the addon itself).

**Comment by Milli-Maci** [comment]
> > I have to give an update.
> > On the first day, almost all episodes could be played. On the second day half of them stopped working and now none plays anymore. On the second day, I even got strange messages as "episode banned" on some of the episodes in de 22nd season.
> 
> Configuration?

I've tried most of them.
Location: US, UK and DE. 
Lang: EN
CC: ON and OFF

Not a single episode works anymore. On season 22, some episodes still say 'banned episode'. 
I live in Belgium and southpark.cc.com works in Chrome.
Maybe something is up with my Kodi but this is the only add-on that's not working and the old add-on was working.
If you need more specific information about my Kodi install, please ask.

**Comment by wargio** [comment]
> > > I have to give an update.
> > > On the first day, almost all episodes could be played. On the second day half of them stopped working and now none plays anymore. On the second day, I even got strange messages as "episode banned" on some of the episodes in de 22nd season.
> > 
> > 
> > Configuration?
> 
> I've tried most of them.
> Location: US, UK and DE.
> Lang: EN
> CC: ON and OFF
> 
> Not a single episode works anymore. On season 22, some episodes still say 'banned episode'.
> I live in Belgium and southpark.cc.com works in Chrome.
> Maybe something is up with my Kodi but this is the only add-on that's not working and the old add-on was working.
> If you need more specific information about my Kodi install, please ask.

which episodes?

**Comment by Matheos96** [comment]
> > > I have to give an update.
> > > On the first day, almost all episodes could be played. On the second day half of them stopped working and now none plays anymore. On the second day, I even got strange messages as "episode banned" on some of the episodes in de 22nd season.
> > 
> > 
> > Configuration?
> 
> I've tried most of them.
> Location: US, UK and DE.
> Lang: EN
> CC: ON and OFF
> 
> Not a single episode works anymore. On season 22, some episodes still say 'banned episode'.
> I live in Belgium and southpark.cc.com works in Chrome.
> Maybe something is up with my Kodi but this is the only add-on that's not working and the old add-on was working.
> If you need more specific information about my Kodi install, please ask.

The "Banned", I believe is because they are actually not available in your region because of one reason or another. You could compare the banned episodes in browser to on kodi. For me, banned episodes are not playable in browser either.

**Comment by Milli-Maci** [comment]
s22e5 will give banned message in Kodi but not in browser.

**Comment by wargio** [comment]
> s22e5 will give banned message in Kodi but not in browser.

yes, because in US actually that episode is not available. i'm trying to fix this right now by adding an "European" geoloc.

**Comment by wargio** [comment]
0.6.3 will introduce the European English streams.
- Matrix https://github.com/xbmc/repo-plugins/pull/3164
- Helix https://github.com/xbmc/repo-plugins/pull/3165

If you want to do a manual update:
- Py2 https://github.com/wargio/plugin.video.southpark_unofficial/archive/python2.zip
- Py3 https://github.com/wargio/plugin.video.southpark_unofficial/archive/master.zip

**Comment by Milli-Maci** [comment]
So an update.
I started doubting my Kodi install because I played around with it quite a bit. I wanted to start fresh so I installed Marjaro XFCE to get things up and running fast (instead of Arch). I set up everything and installed the SP addon. It was still 0.6.2 that I installed two days ago and it worked. Setting my location to UK allowed me to even play s22e5. Happy!
After two days of usage, I wanted to switch back to KDE because XFCE didn't play nice with my refresh rate. Re-installed Manjaro KDE and set Kodi up again. Everything the same. Installed 0.6.3 now and set my location to Europe. Well nothing plays anymore.
Is it even possible that KDE is the problem? Impossible right?

**Comment by wargio** [comment]
> So an update.
> I started doubting my Kodi install because I played around with it quite a bit. I wanted to start fresh so I installed Marjaro XFCE to get things up and running fast (instead of Arch). I set up everything and installed the SP addon. It was still 0.6.2 that I installed two days ago and it worked. Setting my location to UK allowed me to even play s22e5. Happy!
> After two days of usage, I wanted to switch back to KDE because XFCE didn't play nice with my refresh rate. Re-installed Manjaro KDE and set Kodi up again. Everything the same. Installed 0.6.3 now and set my location to Europe. Well nothing plays anymore.
> Is it even possible that KDE is the problem? Impossible right?

Try with the US streams. unfortunately the way the streams works depends also by country. :/

**Comment by Milli-Maci** [comment]
Tried US, EU and DE and none of them works.
I find it so odd that 0.6.2 worked on XFCE. 
But I do understand that it has become close to impossible for you to make it work in all countries.

**Comment by Jool-Pi** [comment]
thanks for the 0.6.3 update. It works for me
Pi3: Kodi (Openelec 18.8)
My location: Belgium

**Comment by sudot0ph** [comment]
There is a slight issue with the German location setting. German API shows German episode names with all their ä,ö and ü glory. The website changes the URLs to ae, oe and ue respectively. The plug in, however, does not, leading to pesky ascii encoding issues.

For example: https://www.southpark.de/folgen/lzz69d/south-park-der-suendenwal-staffel-13-ep-11

Watching the same episode (s13e11) on Kodi set to Germany will lead to the error described.

**Comment by wargio** [comment]
thanks for reporting this! this can be easily patched! I'll try this weekend (if time will allow me) to fix various bugs and add more support!

**Comment by gitgitgitg** [comment]
> thanks for reporting this! this can be easily patched! I'll try this weekend (if time will allow me) to fix various bugs and add more support!

Hi,
are there any updates in solution for this "Umlaute" problem?

**Comment by wargio** [comment]
should be fixed now. please check that i did not mess up the german words.

**Comment by gitgitgitg** [comment]
No sorry. Version 0.6.3 still does not start episodes which title contains any of the German Umlaute "äöüß".

**Comment by wargio** [comment]
be sure to clear the cache (there is an option in the addon settings)

**Comment by gitgitgitg** [comment]
Thank you. Clearing the Cache solved it.
